"""markdown_html: convert the converter's markdown subset to editor-paste HTML + ops.

The markdown is generated by converter.py (not arbitrary), so these assert the exact
subset it emits: headings, **bold**/_italic_/`code`/links, fenced code (verbatim, may
contain blank lines), lists, and inline images split into upload operations.
"""

from __future__ import annotations

from gdoc_to_medium.medium.markdown_html import (
    ImageOp,
    PasteOp,
    markdown_to_html,
    to_operations,
)


def _html(md: str) -> str:
    return markdown_to_html(md)


def test_headings_map_to_h1_through_h6():
    assert _html("# Title") == "<h1>Title</h1>"
    assert _html("## Sub") == "<h2>Sub</h2>"
    assert _html("###### Deep") == "<h6>Deep</h6>"


def test_inline_bold_italic_code_link():
    assert _html("a **b** c") == "<p>a <strong>b</strong> c</p>"
    assert _html("a _b_ c") == "<p>a <em>b</em> c</p>"
    assert _html("use `x = 1` here") == "<p>use <code>x = 1</code> here</p>"
    assert _html("[Medium](https://medium.com)") == '<p><a href="https://medium.com">Medium</a></p>'


def test_code_span_contents_are_not_reinterpreted_and_are_escaped():
    # Backticked content must not become bold/italic and < > are escaped.
    assert _html("`a **b** <c>`") == "<p><code>a **b** &lt;c&gt;</code></p>"


def test_plain_text_is_html_escaped():
    assert _html("1 < 2 & 3 > 0") == "<p>1 &lt; 2 &amp; 3 &gt; 0</p>"


def test_unordered_and_ordered_lists():
    assert _html("- one\n- two") == "<ul><li>one</li><li>two</li></ul>"
    assert _html("1. one\n1. two") == "<ol><li>one</li><li>two</li></ol>"


def test_fenced_code_block_preserves_blank_lines_and_is_verbatim():
    md = "```\nline1\n\nline3\n```"
    assert _html(md) == "<pre><code>line1\n\nline3</code></pre>"


def test_fence_with_language_indent_and_specials_escaped():
    md = "```\nif a < b:\n    return '<x>'\n```"
    assert _html(md) == "<pre><code>if a &lt; b:\n    return &#x27;&lt;x&gt;&#x27;</code></pre>"


def test_multiple_blocks_concatenate_in_order():
    md = "# T\n\nfirst\n\n- a\n- b"
    assert _html(md) == "<h1>T</h1><p>first</p><ul><li>a</li><li>b</li></ul>"


def test_to_operations_splits_images_into_image_ops():
    url = "https://gdoc2medium.local/img/1.png"
    ops = to_operations(f"Intro\n\n![a cat]({url})\n\nOutro")
    assert ops == [
        PasteOp("<p>Intro</p>"),
        ImageOp(url=url, alt="a cat"),
        PasteOp("<p>Outro</p>"),
    ]


def test_to_operations_image_inline_within_paragraph():
    url = "https://gdoc2medium.local/img/2.gif"
    ops = to_operations(f"see ![pic]({url}) here")
    assert ops == [
        PasteOp("<p>see</p>"),
        ImageOp(url=url, alt="pic"),
        PasteOp("<p>here</p>"),
    ]


def test_to_operations_code_block_is_single_paste_op():
    ops = to_operations("```\nx = 1\n```")
    assert ops == [PasteOp("<pre><code>x = 1</code></pre>")]


def test_to_operations_empty_markdown_is_no_ops():
    assert to_operations("") == []
    assert to_operations("   \n\n  ") == []


def test_snake_case_is_not_italicized():
    # Underscores inside a word must not become emphasis (dev prose is full of these).
    assert _html("call file_name_here.py now") == "<p>call file_name_here.py now</p>"
    assert _html("use my_var and your_var") == "<p>use my_var and your_var</p>"


def test_real_italic_still_works():
    assert _html("a _real phrase_ b") == "<p>a <em>real phrase</em> b</p>"
    assert _html("_leading_ and trailing _ok_") == "<p><em>leading</em> and trailing <em>ok</em></p>"


def test_heading_with_inline_image_keeps_structure_no_literal_hashes():
    url = "https://gdoc2medium.local/img/1.png"
    ops = to_operations(f"## Look ![cat]({url}) here")
    assert len(ops) == 1
    html = ops[0].html
    assert html.startswith("<h2>") and html.endswith("</h2>")
    assert "<img" in html
    assert "##" not in html  # the heading marker never leaks into the body


def test_list_with_inline_image_keeps_list_structure():
    url = "https://gdoc2medium.local/img/2.png"
    ops = to_operations(f"- item ![x]({url})")
    assert len(ops) == 1
    assert ops[0].html.startswith("<ul><li>")
    assert "- " not in ops[0].html
